geshan/au-companies-providing-work-visa-sponsorship

.github/PULL_REQUEST_TEMPLATE.md
CODE_OF_CONDUCT.md
CONTRIBUTING.md
CRITERIA.md
README.md

Adds 12 companies

---

README.md

Removing Lendi adding some disclaimer

---

README.md

Adding Tyro

---

README.md

IRESS has been added to list. Taken from stackoverflow

---

README.md

Adding zendesk

---

README.md

Add BCG Digital Ventures

---

README.md

Adds wisetech global

---

README.md

Adds domain group

---

README.md

Adds switch media

---

README.md

Adds rockend

---

README.md

Adds expert360

---

README.md

Adds spaceship

---

README.md

Adds REA Group

---

README.md

Changes to REA tech stack

---

README.md

Adds Learnosity

---

README.md

Adds bigcommerce

---

README.md

Add Optiver

---

README.md

Adds healthshare

---

README.md

Adds HireUp

---

README.md

Adds Propeller aero

---

README.md

Add your employer appeal :)

---

README.md

Searchable sort-able and group-able list

---

README.md

Adds Local measure

---

README.md

Adds Zip Money

---

README.md

Typo fix for available

---

README.md

- [x ] I agree to the [Code of Conduct](https://github.com/geshan/au-companies-providing-work-visa-sponsorship/blob/master/CODE_OF_CONDUCT.md)

Adds Oppizi

---

README.md

CSIRO's Data61 added from stackoverflow.

---

README.md

Applaud UK immigration dept

---

README.md

Add Expedia Group

---

README.md

Reorder Expedia Group

---

README.md

Add Finder

---

README.md

Change Expedia link

---

README.md

Adding Elmo HR and payroll

---

README.md

Adds papercut software

---

README.md

Adds Koala

---

README.md

Adds Split payments

---

README.md

Adds say thanks

---

README.md

Adds pragmateam

---

README.md

Adds Glamcorner

---

README.md

Reorder Qwilr

---

README.md

Adds 2 companies on the list

---

README.md

Change Healthshare career's link

---

README.md

Adds RedBubble to the list

---

README.md

Add clipchamp

---

README.md

Add Brighte

---

README.md

Add Sydney to digio

---

README.md

Add HeadUp Labs

---

README.md

Add Home Care Heroes

---

README.md

Adding shippit

---

README.md

Add Simply Wall St

---

README.md

Add DriveYello

---

README.md

Add Harrison.ai

---

CONTRIBUTING.md
README.md

fix typo and format JavaScript consistency

---

README.md

Add PDF list of 1000s of companies that sponsored work visa circa 2020

---

README.md

Fix typo on 70 page pdf list of companies

---

README.md

Update README.md and add Rokt

---

README.md

Add SquareUp

---

README.md

Firefox says the link for Oliver Wyman Labs is a potential security risk. So I am removing it and opening a PR. Screenshot available [here.](https://github.com/geshan/au-companies-providing-work-visa-sponsorship/issues/100)

 Firefox says one of the links is suspicious

---

README.md

The career link has been changed.

chore: Update PaperCut link in README.md

---

README.md

---
I myself work at Nine as an engineer and have multiple colleagues being sponsored by the company. Sponsorship can be with subclass 482 and 186.
1. Start with HR over the phone
2. Technical interview (data structure and algorithm; system design if senior role)
3. Behavioural interview with 2-3 engineering managers

Add Nine to the list

---

README.md

Fixed URLs

---

README.md

Removes Simply Wall st.

---

README.md

* Rebranded to Mantel Group, not sure if Mantel Group also does visa sponsoring

Removes Dig.io

---

README.md

Replaces Quantium jobs page

---

README.md

Removes BCG

---

README.md

Fix easy go careers' page

---

README.md

Fixes #138, #133 & #132
Because links are working as expected.

Update Oppizi job link in README.md

---

README.md

feat: add linktree
